#!/usr/bin/env python3
"""
i18n_make
=========

Make half of the sprezzature-ui unified-i18n rule: establish
``locales/i18n.yaml`` as the single per-project source of truth for
translatable strings — GUI labels and LLM prompts — and emit the glue so a
vanilla-JS sprezzature end and a Python prompt loader read from it instead of
hardcoding strings.

Three deterministic steps (all run by default; select one with a flag):

1. scaffold — create ``locales/i18n.yaml`` if it is missing, with the
   declared ``locales`` and a couple of example ``gui:`` / ``prompts:`` entries.
2. compile — read ``locales/i18n.yaml`` and write ``locales/i18n.json``
   (browsers cannot parse YAML; the JS runtime fetches the JSON).
3. emit-loader — write ``locales/i18n.js``, a small framework-free ES module
   that fetches ``i18n.json`` and exposes ``initI18n(locale)`` + ``t(id)``.

Its counterpart is :mod:`audit_i18n` (the audit half), which flags strings that
live in code instead of ``locales/i18n.yaml``.

Usage
-----
::

    # Full scaffold in ./locales (init if missing, compile, emit loader)
    python i18n_make.py

    # Point at a project root; only re-compile YAML -> JSON
    python i18n_make.py --dir path/to/project --compile

    # In the browser:  import { initI18n, t } from "./locales/i18n.js";
    #                   await initI18n(); el.textContent = t("app.title");

Author
------
`Warith Harchaoui, Ph.D. <https://www.linkedin.com/in/warith-harchaoui/>`_
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _argparse import make_parser  # noqa: E402

#: Starter catalog written by --init. One namespace for GUI strings, one for
#: prompts — both are the same message in language X.
_STARTER: Dict[str, Any] = {
    "locales": ["en", "fr"],
    "gui": {
        "app.title": {"en": "My App", "fr": "Mon application"},
        "action.save": {"en": "Save", "fr": "Enregistrer"},
        "empty.no_results": {"en": "No results yet", "fr": "Aucun résultat pour l'instant"},
    },
    "prompts": {
        "summarize.system": {
            "en": "You are a concise assistant. Summarise the input in three bullet points.",
            "fr": "Vous êtes un assistant concis. Résumez l'entrée en trois puces.",
        },
    },
}

#: The vanilla-JS runtime emitted by --emit-loader. Framework-free ES module;
#: reads the compiled JSON, honours <html lang>, falls back to the first locale
#: then to the message id. Kept as source here so the make step is deterministic.
_LOADER_JS = '''\
// i18n.js — load locales/i18n.json (compiled from locales/i18n.yaml, the single
// source of truth for GUI strings AND prompts) and translate by message id.
// Strings live in YAML, never hardcoded here. Generated by sprezzature-ui i18n_make.
let CATALOG = { locales: ["en"], gui: {}, prompts: {} };
let LOCALE = "en";

// Fetch the compiled catalog once. Call before the first t(); returns the
// catalog so callers can also read prompts (CATALOG.prompts[id][locale]).
export async function initI18n(locale) {
  const res = await fetch(new URL("./i18n.json", import.meta.url));
  CATALOG = await res.json();
  LOCALE = locale
    || document.documentElement.getAttribute("lang")
    || (CATALOG.locales && CATALOG.locales[0])
    || "en";
  return CATALOG;
}

// Translate a GUI message id. Falls back to the source locale, then the id
// itself, so a missing key degrades visibly instead of throwing.
export function t(id, locale = LOCALE) {
  const entry = (CATALOG.gui && CATALOG.gui[id]) || {};
  const src = (CATALOG.locales && CATALOG.locales[0]) || "en";
  return entry[locale] ?? entry[src] ?? id;
}

// Current locale (read-only helper for callers that render lang-dependent UI).
export function currentLocale() { return LOCALE; }
'''


def scaffold(catalog: Path) -> bool:
    """Create ``locales/i18n.yaml`` with the starter catalog if it is absent.

    Parameters
    ----------
    catalog : pathlib.Path
        Target ``locales/i18n.yaml`` path.

    Returns
    -------
    bool
        ``True`` if the file was created, ``False`` if it already existed
        (never overwrite a real catalog).
    """
    if catalog.exists():
        return False
    catalog.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# locales/i18n.yaml — single source of truth for translatable strings.\n"
        "# One entry per message id; one sub-key per declared locale. Serves the\n"
        "# GUI (gui:) AND the LLM prompts (prompts:). Never hardcode a string in\n"
        "# JS or inline a prompt in Python — add it here and load it.\n"
    )
    catalog.write_text(
        header + yaml.safe_dump(_STARTER, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
    return True


def compile_json(catalog: Path) -> Path:
    """Compile ``locales/i18n.yaml`` to ``locales/i18n.json`` for the browser.

    Parameters
    ----------
    catalog : pathlib.Path
        Source ``locales/i18n.yaml``.

    Returns
    -------
    pathlib.Path
        The written ``locales/i18n.json`` path.

    Raises
    ------
    SystemExit
        If the catalog does not exist (run ``--init`` first).
    """
    if not catalog.exists():
        sys.exit(f"No catalog at {catalog}. Run with --init first.")
    data = yaml.safe_load(catalog.read_text(encoding="utf-8")) or {}
    out = catalog.with_suffix(".json")
    # Sort keys for a deterministic, diff-stable build artifact.
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
                   encoding="utf-8")
    return out


def emit_loader(catalog: Path) -> Path:
    """Write the framework-free ``locales/i18n.js`` runtime next to the catalog.

    Parameters
    ----------
    catalog : pathlib.Path
        The catalog path (used only to locate the ``locales/`` dir).

    Returns
    -------
    pathlib.Path
        The written ``locales/i18n.js`` path.
    """
    js = catalog.parent / "i18n.js"
    js.parent.mkdir(parents=True, exist_ok=True)
    js.write_text(_LOADER_JS, encoding="utf-8")
    return js


def main() -> int:
    """CLI entry point.

    Returns
    -------
    int
        Always 0 on success (make operations either act or no-op idempotently).
    """
    p = make_parser(
        prog="sprezzature-ui-i18n-make",
        description="Scaffold + compile locales/i18n.yaml (GUI strings + prompts) "
                    "and emit a vanilla-JS loader — the make half of the i18n rule.",
        epilog=__doc__,
    )
    p.add_argument("--dir", default=".", help="Project root (catalog is <dir>/locales/i18n.yaml).")
    p.add_argument("--init", action="store_true", help="Only scaffold the catalog if missing.")
    p.add_argument("--compile", action="store_true", help="Only compile YAML -> JSON.")
    p.add_argument("--emit-loader", action="store_true", help="Only emit locales/i18n.js.")
    args = p.parse_args()

    catalog = Path(args.dir) / "locales" / "i18n.yaml"
    # No explicit step flag => do the whole scaffold (init + compile + loader).
    do_all = not (args.init or args.compile or getattr(args, "emit_loader"))

    if args.init or do_all:
        created = scaffold(catalog)
        print(f"{'created' if created else 'kept existing'} {catalog}")
    if args.compile or do_all:
        out = compile_json(catalog)
        print(f"compiled {out}")
    if getattr(args, "emit_loader") or do_all:
        js = emit_loader(catalog)
        print(f"emitted {js}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
